name: Stable Release

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  release:
    uses: https://codeberg.org/Conduction/.github/.forgejo/workflows/release-stable.yml@main
    with:
      app-name: softwarecatalog
    secrets:
      CODEBERG_TOKEN:             ${{ secrets.CODEBERG_TOKEN }}
      NEXTCLOUD_SIGNING_KEY:      ${{ secrets.NEXTCLOUD_SIGNING_KEY }}
      NEXTCLOUD_SIGNING_CERT:     ${{ secrets.NEXTCLOUD_SIGNING_CERT }}
      NEXTCLOUD_APPSTORE_TOKEN:   ${{ secrets.NEXTCLOUD_APPSTORE_TOKEN }}
