name: Code Quality

on:
  push:
    branches: [main, development, feature/**, bugfix/**, hotfix/**]
  pull_request:
    branches: [main, master, development]

jobs:
  quality:
    uses: ConductionNL/.github/.github/workflows/quality.yml@main
    with:
      app-name: softwarecatalog
      php-version: "8.3"
      nextcloud-ref: stable32
      enable-psalm: true
      enable-phpstan: true
      enable-phpmetrics: true
      enable-frontend: true
      enable-phpcs: false
      enable-eslint: true
      enable-phpunit: true
      enable-newman: false
      additional-apps: '[{"repo":"ConductionNL/openregister","app":"openregister"}]'
