name: Documentation

on:
  push:
    branches: [development]
  pull_request:
    branches: [development]

jobs:
  deploy:
    uses: ConductionNL/.github/.github/workflows/documentation.yml@main
    with:
      cname: softwarecatalog.conduction.nl
