name: Documentation

on:
  push:
    branches: [documentation]
  pull_request:
    branches: [documentation]

jobs:
  deploy:
    uses: Conduction/.github/.github/workflows/documentation.yml@main
    with:
      cname: softwarecatalog.conduction.nl
