name: Release Beta

on:
  push:
    branches:
      - beta

jobs:
  release:
    uses: ConductionNL/.github/.github/workflows/release-beta.yml@main
    with:
      app-name: softwarecatalog
    secrets: inherit
