name: SBOM

on:
  push:
    branches: [main, beta, development]

jobs:
  sbom:
    uses: ConductionNL/.github/.github/workflows/quality.yml@main
    with:
      app-name: softwarecatalog
      enable-sbom: true
      enable-frontend: true
